import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    
    <html lang="en">
      <body>
          <header>
            <nav className="bg-blue">
              <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
                <a className="flex items-center space-x-3 rtl:space-x-reverse">
                    <img src="http://localhost:3000/images/football.png" className="h-8" alt="TicketVerse Logo" />
                    <span className="self-center text-2xl font-semibold whitespace-nowrap header-text">Ticket Verse</span>
                </a>
                <div className="hidden w-full md:block md:w-auto" id="navbar-default">
                  <button 
                  className="inline-flex justify-center hover:text-gray-900 items-center py-3 px-5 sm:ms-4 text-base font-medium 
                  text-cente rounded-lg border border-red hover:bg-gray-100 focus:ring-4
                  focus:ring-gray-400">Connect Wallet</button>
                  {/* <a href="#" className="inline-flex justify-center hover:text-gray-900 items-center py-3 px-5 sm:ms-4 text-base font-medium text-cente rounded-lg border border-red hover:bg-gray-100 focus:ring-4 focus:ring-gray-400"
                   >
                            Connect Wallet
                  </a>        */}
                </div>
              </div>
            </nav>
          </header>
           {children}
          <footer className="bg-blue">
              <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
                <div className="sm:flex sm:items-center sm:justify-between">
                    <span className="text-sm sm:text-center text-color-white">Copyright © 2024 NoobLink Ninjas. All Rights Reserved.
                    </span>
                </div>
              </div>
          </footer>
        </body>
    </html>
 
  );
}
